---
# defaults file for letsbuilda.server.soc

sys_packages:
  - python3-virtualenv
  - libssl-dev

projects:
  - name: dragonfly
    repo: "https://github.com/SkeletalDemise/DragonFly.git"
    dest: "/opt/soc/dragonfly"
