apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: dragonfly
  name: dragonfly-loader
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dragonfly-loader
            image: ghcr.io/vipyrsec/dragonfly-loader:edge
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: dragonfly-loader-env
