apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: dragonfly
  name: dragonfly-loader
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dragonfly-loader
            image: ghcr.io/vipyrsec/dragonfly-loader:11030a287f9db03e23afa75c997b88b3f6388c3e
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: dragonfly-loader-env
          restartPolicy: Never
